### ISSUE TITLE
CI: Remind people of adding an entry to `CHANGELOG`

### ISSUE THREAD

**Issue by bkchr** [polkadot-fellows/runtimes#143]
It should be somehow possible to skip this, ideas are welcome.

**Comment by Bullrich** [comment]
What about a modifying the [pull_request_template](https://github.com/polkadot-fellows/runtimes/blob/main/.github/pull_request_template.md) to inform the users of the requirement?

Could be something like:

```markdown
<!-- Remember that you can run `/merge` to enable auto-merge in the PR -->

## Checklist
Did you remember to modify the `CHANGELOG.md` file?
- [ ] Yes
```

---

The other option is to generate a simple action that can see if the `CHANGELOG` file has _not_ been modified and either, comment on the creation of a PR that the file has not been modified, or, fail until the `CHANGELOG` file has been modified.

**Comment by Bullrich** [comment]
> The other option is to generate a simple action that can see if the `CHANGELOG` file has _not_ been modified and either, comment on the creation of a PR that the file has not been modified, or, fail until the `CHANGELOG` file has been modified.

Example using: [pr-includes-file-change](https://github.com/marketplace/actions/pr-includes-file-change):

```yml
name: Modify Changelog

on:
  pull_request_target:
    types:
      - opened

jobs:

  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - name: Get Changed Files
        id: changed
        uses: foodee/pr-includes-file-change@master
        with:
          paths: ^CHANGELOG.md
      - name: Comment lack of CHANGELOG
        if: steps.changed.outputs.matched != 'true'
        run: gh pr comment $PR_NUMBER --body "Please modify the CHANGELOG.md file 🗂️"
        env:
          PR_NUMBER: context.issue.number
      - name: Fail
        if: steps.changed.outputs.matched != 'true'
        run: exit 1
```

Disclaimer, I haven't tested this action.
